#!/bin/bash
##############################################################################
# Simple Interactive Selective Shell
#        provides a simple menu (cp Thomas Schneider 2020-2025)
#
# usage: sishell <name> [file-name or wildcard] [-s <list>] [subst=true] [BANNER=<banner>]
#             [EDITOR=<editor>] [before=<clear>] [log=true]
# - name        : will be used as variable name and to read the file '$1.lst'
# - file-or-glob: if wildcard, select from file-list, else menu file name
# - -s "..."    : simple list separated by spaces
# - subst=true  : variables of your menu list file will be substituted
# - BANNER=<banner>: use <banner> instead of figlet
# - EDITOR=<editor>: use <editor> instead of vim
# - before=<clear> : (default:clear) do something between init and menu start
# - log=true       : redirects 'echo' to 'printf | tee log'
#
# - each line has structure: COMMAND # DESCRIPTION
#   with:
#    - COMMAND as any shell command. e.g.: 'sishell' for recursion 
#      'read' for input or 'echo' for printing result
#      for complex/unreadable commands, define your own aliases or functions!
#    - DESCRIPTION starting with the character '#' any comment for the comment
# - examples:
#    - sishell myfile         # will read file myfile.lst as list
#    - sishell myfile xyz.sh  # used variable myfile and read list from xyz.sh
#    - sishell myfile "*.txt" # select a file from *.txt, result is in $myfile
#
# you may use the folowing convenience methods in your menu list file:
#    run, input, inrun, choose, edit, ffind, show, sysinfo
# NOTE: 
#    - if figlet is installed, an ascii title will be printed
#    - if the file 'sishell-alias.sh' was found it will be loaded
#    - finally, the file 'sishell-$USERNAME.sh' with results will be created
##############################################################################

title=<<EOF
 ____ ___ ____  _          _ _ 
/ ___|_ _/ ___|| |__   ___| | |
\___ \| |\___ \| '_ \ / _ \ | |
 ___) | | ___) | | | |  __/ | |
|____/___|____/|_| |_|\___|_|_|
                               
EOF

echo "starting: $0 $@"
[ "$1" == "" ] || [ "$1" == "--help" ] && head -n 35 $0 && exit 1
read rows cols < <(stty size) # TODO: use terminal size
used_variables=$(sed -nE  's/.*\$\{*(\w+).*/\1/p' $0 | sort | uniq | tr '\n' ' ')
echo "used variables are: $used_variables"
# TODO: check if par is var: if [[ " $used_variables " == *" ${x} "* ]];
echo -en "setting parameters: "; for a in "$*" ; do [[ "$a" == *"="* ]] && declare -gt $a && echo $a; done;

SELF=$(basename $0); SELF=${SELF%.*};
[ "$log" == "true" ] && echo() { printf "%s\n" $* | tee -a $ENV_DIR/$SELF.log; }
run() { bash "$@"; }
input() { read -ep ": " -i "${!1}" edt; declare -g $1="$edt"; echo "$1=\"$edt\"" >> $ENV_DIR/$SELF-$USERNAME.def; } 
inrun() { input $1; eval "${!1}"; }
choose() { bash $SELF "$@"; }
edit() { ${EDITOR:-vim} "$*"; }
ffind() { find ~/ -type f -name "$1" -mtime $2 -exec grep "$3" {} \; -exec echo {} \; | xargs edit; }
show() { echo "$@"; }
sysinfo() { uname -a; id; free; df -TPh; ifconfig; ipconfig; lscpu; lsblk; lshw -short; lspci; fdisk -l;}
# log() { eval "$*" >> $ENV_DIR/$SELF.log; edit $ENV_DIR/$SELF.log; }

bar__() { for i in {1..26}; do printf "%s" $1; done; }
printbar() { printf "$C_FRM<"; bar__ "-"; printf "|%14s%-14s|" $1 $2; bar__ "-"; printf ">%s$R" $'\n'; }
initcolors() {
	E0="\x1b[00;" E1="\x1b[01;" I=30
	COLORS="RED GREEN YELLOW BLUE PURPLE CYAN LIGHTGRAY"
	for c in $COLORS; do I="$(($I+1))"; declare -gx $c="$E0$I""m"; declare -gx "L$c"="$E0$I""m"; echo "L$c=$E1$I""m"; done;
	export C_FRM=$LBLUE; export C_CMD=$LCYAN; export C_PAR=$LGREEN; export C_CMT=$LRED; export RESTORE='\x1b[0m'; export R=$RESTORE
}
setcolors() { echo "$1" | sed -nEe "s/(\w+|[#-]+)(.*)(([#]|[-]{2}).*)/$C_CMD\1$C_PAR\2$C_CMT\3$R/p"; }

create_env() {
	[ -e $1 ] && ENV_DIR=".$SELF.$(basename $1)" || ENV_DIR=".$SELF.$1"

	if [ ! -e $ENV_DIR ]; then
		echo "first start -> creating environment \"$ENV_DIR\""
		mkdir $ENV_DIR
		cp $(dirname $0)/$SELF-*.sh  $ENV_DIR
		cp $(dirname $0)/$SELF-*.def $ENV_DIR
		cp $(dirname $0)/$SELF-*.lst $ENV_DIR
	fi
	[ -e $SELF-alias.sh ] && source $SELF-alias.sh
	[ -e $ENV_DIR/$SELF-alias.sh ] && source $ENV_DIR/$SELF-alias.sh
	[ -e $ENV_DIR/$SELF-defaults.def ] && source $ENV_DIR/$SELF-defaults.def
	[ -e $ENV_DIR/$SELF-$USERNAME.def ] && source $ENV_DIR/$SELF-$USERNAME.def

}

menu_main() { 
	NAME=$1
	PAGE=${2:-1}
	IFS_=$IFS

	case $2 in 
		*[*]*) LIST=$2;; 
		*[.]*) LIST=$(< $2);; 
		*) [  -e $NAME ] && LIST=$(< $NAME) && (NAME=$(basename $NAME); NAME=${NAME%%.*}) || LIST=$(< $NAME.lst) ;; 
	esac
	[ "$subst" == "true" ] && LIST=$(printf "$LIST" | envsubst "$(set -o posix; set)")
	[ "$2" != "-s" ] && [ "$3" != "-s" ] && [[ "$2" != *"*"* ]] && RUNLINE="true" && IFS=$'\n' && LIST=$(setcolors "$LIST") || RUNLINE="false"
	PS3="$(printbar " PAGE $PAGE - PLEASE SELECT" " 1..$(echo "$LIST" | wc -l)") "$'\n'": "

	BANNER=${BANNER:-figlet}
	ascii_banner_installed=$(which $BANNER) # on cygwin, 'which' prints always the path
	eval "${before:-clear}"
	echo -en $LYELLOW
	if [ "$ascii_banner_installed" != "" ]; then $BANNER "$NAME"; else head -n 42 $0 | tail -n 6; fi
	printbar " PAGE $PAGE - PLEASE SELECT" " $NAME"
	select i in $LIST ; do 
		[ "$i" == "" ] || [ "$i" == "0" ] && break
		PAGE=$(($PAGE+1))
		IFS=$IFS_
		CMD=${i%#*}
		CMD=$(echo "$CMD" | sed 's/\x1b\[[0-9;]*m//g')
		echo -en $C_FRM$CMD$R
		[ "$CMD" != "" ] && declare -x $NAME="$CMD";
		[ "$RUNLINE" == "true" ] && eval "$CMD" || break
	done
	echo "${NAME% *}=\"$CMD\"" >> $ENV_DIR/$SELF-$USERNAME.def
	printbar "$NAME: " "$CMD"
}

initcolors
create_env $1
menu_main "$@" "$PAGE"
